@php use Illuminate\Support\Str; @endphp
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Posts - DevForum</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
</head>

<body class="bg-light">

    @include('nav')

    <div class="container mt-4">
        
        <h2 class="mb-4">All Posts</h2>

        <div class="row">
            @forelse ($posts as $post)
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card h-100 shadow-sm hover-card">
                        <div class="card-body">
                            
                            {{-- Title --}}
                            <h5 class="card-title">
                                <a href="{{ route('posts.show', $post->id) }}"
                                   class="text-decoration-none text-dark stretched-link">
                                    {{ $post->title }}
                                </a>
                            </h5>
                            
                            {{-- Meta Data --}}
                            <div class="card-subtitle mb-3 text-muted small">
                                By <span class="fw-bold">{{ $post->user->username }}</span>
                                &bull; 
                                {{ $post->created_at->format('M d, Y') }}
                            </div>
                            
                            {{-- Body Snippet --}}
                            <p class="card-text text-secondary">
                                {{ Str::limit($post->body, 100) }}
                            </p>
                        </div>
                        
                        {{-- Footer (Stats) --}}
                        <div class="card-footer bg-white border-top-0 d-flex justify-content-between text-muted small pb-3">
                            <div>
                                <i class="bi bi-eye"></i> {{ $post->views }}
                            </div>
                            <div>
                                <span class="text-success me-2">
                                    <i class="bi bi-arrow-up"></i> {{ $post->upvotes }}
                                </span>
                                <span class="text-danger">
                                    <i class="bi bi-arrow-down"></i> {{ $post->downvotes }}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                {{-- If no posts exist --}}
                <div class="col-12">
                    <div class="alert alert-info text-center">
                        No posts found. Be the first to <a href="{{ route('posts.create') }}">create one!</a>
                    </div>
                </div>
            @endforelse
        </div>

        {{-- Pagination Links (Automatically generated by Laravel) --}}
        <div class="d-flex justify-content-center mt-4">
            {{ $posts->links() }}
        </div>
        
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('js/change_active_navbar_link.js') }}"></script>

</body>
</html>